name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP archive
        run: |
          cd custom_components
          zip -r ../tianxing_api.zip tianxing_api

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./tianxing_api.zip
          asset_name: tianxing_api.zip
          asset_content_type: application/zip
